# -*- coding: utf-8 -*-
"""TEMPLATE_IRIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I71J5stDNh-7wxwqi_B9IcUtpTTk0Zwz

IMPORT LIBRARY YANG DIBUTUHKAN
"""

from __future__ import print_function

import IPython
print('IPython:', IPython.__version__)
import numpy
print('numpy:', numpy.__version__)
import pandas
print('pandas:', pandas.__version__)
import sklearn
print('scikit-learn:', sklearn.__version__)

"""**LOAD DATA IRIS** bawaan asli (built-in) dari modul sklearn.datasets di dalam library scikit-learn"""

from sklearn.datasets import load_iris
iris = load_iris()

"""MENAMPILKAN TIPE DATA NUMPY ARRAY DAN PANDAS DATAFRAME"""

#Mengetahui tipe data  -> bawaanya type datanya numpy array
X,y = iris.data, iris.target
type(X)

numpy.ndarray

# data numpy dan contoh 5 data terbatas dan labelnya
X, y = iris.data, iris.target

print(X[:5])
print(y[:5])

#menampilkan data pandas dataframe
# data pandas
import pandas as pd

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target #target

df.head()

#melakukan preprocessing (cek data kosong,duplikat,outlier dll)

"""MEMBUAT PIPELINE UNTUK NUMPY DAN PANDAS"""

# buat pipeline untuk data numpy
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

pipe_numpy = make_pipeline(StandardScaler(), LinearSVC())
pipe_pandas= make_pipeline(StandardScaler(), LinearSVC())

"""MELAKUKAN SPLITTING"""

#splitting
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

#split dataset
#numpy (ada 4 parameter karena antara kolom dan label dibedakan)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=46)

# pandas (kolom dan label disatukan)
df_train, df_test = train_test_split(df, test_size=0.2, random_state=46)

"""MELAKUKAN TRAINING"""

#training
#numpy (dilakukan scaling dan model)
pipe_numpy.fit(X_train, y_train)
y_pred=pipe_numpy.predict(X_test)
print(classification_report(y_test, y_pred))

#training
#pandas
X_train_df, y_train_df = df_train.drop('target', axis=1), df_train['target']
X_test_df, y_test_df = df_test.drop('target', axis=1), df_test['target']
pipe_pandas.fit(X_train_df, y_train_df)
y_pred_df = pipe_pandas.predict(X_test_df)
print("Hasil evaluasi Model pandas")
print(classification_report(y_test_df, y_pred_df))

"""SAVE MODEL"""

#save model dengan picle -> menjadi binary file
import pickle

#numpy
with open('model_numpy.pkl', 'wb') as f:
  pickle.dump(pipe_numpy, f)

#pandas
with open('model_pandas.pkl', 'wb') as f:
  pickle.dump(pipe_pandas, f)

"""LOAD MODEL"""

#load model
#numpy

with open('model_numpy.pkl', 'rb') as model_file:
  loaded_model_numpy = pickle.load(model_file)

#load model
#pandas
with open('model_pandas.pkl', 'rb') as model_file:
  loaded_model_pandas = pickle.load(model_file)
#

"""MEMASUKKAN DATA PREDIKSI BARU UNTUK MENCOBA"""

#mencoba memasukkan data baru untuk di prediksi
new_data=[[3,4.2,4,5]]
loaded_model_numpy.predict(new_data)

#mencoba memasukkan data baru untuk memprediksi
new_data_df = pd.DataFrame([[1,1,1,1]], columns=iris.feature_names)
loaded_model_pandas.predict(new_data_df)